### ISSUE TITLE
 [BUG] Profile banner is not visible

### ISSUE THREAD

**Issue by SEYOON0** [finnjosten/Zelk-Discord-Theme-Fixes#14]
**Describe the bug**
If you press the VIEW PROFILE button, you cannot see the banner.

**To Reproduce**
1. Click on 'VIEW PROFILE'
2. See error

**Expected behavior**
Press the VIEW PROFILE button to see the banner of the profile

**Screenshots**
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/143906382/c70ab197-7a09-4733-bd86-8497f3620fa4)
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/143906382/57d4a670-c6c8-41e6-b01c-368976912911)

**Additional context**
I've used all Zelk Discord Theme Fixes, but the banner is still broken

**Comment by finnjosten** [comment]
Thank you for making an issue.

I am aware of this issue, i will be looking into to this.

**Comment by finnjosten** [comment]
This issue seems to be fixed. If it doesnt work please make sure to clear your cache for discord. 

![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/117974776/efc8f3bc-bbf4-42b4-b88e-b536d5a1a0d4)
