### ISSUE TITLE
Visual bug [BUG] 

### ISSUE THREAD

**Issue by itzkrofi** [finnjosten/Zelk-Discord-Theme-Fixes#18]
**Describe the bug**
there is nothing to describe, just look at the photo

![obraz_2023-09-30_203149216](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/54178864/40c9482f-f6ee-43f4-9a12-f40d0009d60d)

**Comment by itzkrofi** [comment]
oh i forgot, can you repair this issue?

**Comment by finnjosten** [comment]
Sorry, was pretty bussy.

Where does this issue pop up for you? So i can try and reproduce it.

please also let me know if you are using any plugins or other themes

**Comment by finnjosten** [comment]
FYI

When making an issue you get this form to fill out, please try an fillout as much as you can next time. This just saves time for you and me!


> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by itzkrofi** [comment]
this issue pop up when i am going to user settings

i am using only zelk theme and this theme fixes

**Comment by finnjosten** [comment]
Hmm i dont seem to have this issue, nvm discord just caching the page

**Comment by finnjosten** [comment]
I added a quick fix, see if this solves your issue

**Comment by itzkrofi** [comment]
nothing changed ;/

**Comment by finnjosten** [comment]
Remerged the branch let me know if that helps (seems to work for me)

**Comment by itzkrofi** [comment]
ye it works thank you so much

**Comment by finnjosten** [comment]
No problem! Thank you for making an issue!
