### ISSUE TITLE
[FR] Disable some visual changes made by the theme

### ISSUE THREAD

**Issue by tmprnc** [finnjosten/Zelk-Discord-Theme-Fixes#35]
I'm not really sure this counts as a feature request nor a bug.
It is more so that this theme adds theming changes beyond fixing glaring visual flaws that I'd rather avoid.
I'm very appreciative of the effort put into fixing old CSS errors, but I'd like if possible to keep the theme as close as possible to the original.

Namely; the main chat UI is a different background color from the rest of the UI. The original Zelk to my knowledge didn't do that, and I preferred it that way.
Furthermore, the slight box-shadow at the bottom of the channel header bar used to be contiguous, all the way to the guild header bar, whereas now it has been replaced with a rounded corner, making channel list, guild header, and channel header into one singular block and sectioning off the chat itself.

![1708437854](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/3785923/397b5847-c738-495b-ad98-ae671a51b5f6)
Fixes applied
![1708438119](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/3785923/cbde5064-2458-4f11-9000-126231c9e745)
Fixes not applied

It also looks a little bizarre on forums/whatever Discord names this feature. To be fair, it is entirely because Zelk itself didn't support those and doesn't re-theme forums accordingly, which explains the color disparity.
![1708437864](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/3785923/d9af84cb-223c-4fd2-aeb9-b97844bf5190)
In that regard, I suppose I am suggesting this one as a bugfix.

I'm not really asking you to change the visuals how you want them on your version of the theme, but I'd be particularly thankful if you could point me to how to revert those specific changes.
What are the CSS classes from the fixes I should modify or comment out? Do the fixes use !important for these settings?
I'd like to avoid having to create a local copy of the fixes in my themes folder instead of an @import, seeing as I'd like to get the updates nonetheless.
If I could simply apply my overrides below the @import in the main .theme.css file, I'd prefer that.

**Comment by finnjosten** [comment]
I will try and move these changes to an addon. Either which disables these changes or which applies these changes depends idk yet.

I indeed agree that some changes are straving a bit away from the original Zelk theme, but I usually try to mix Discord and Zelk a bit.

Thank you for letting me know. I will look into it soon!

**Comment by finnjosten** [comment]
As you may have noticed i have pushed a new update. Although this still does not reflect the screenshots you made is because I have made changes based on screenshots in the Zelk theme. Discord has broken the original a lot so this will be some on going work.
